- chiedere a vlad per la cosa del most frequent nell'advanced imputer

In [10]:
import pandas as pd
import numpy as np
import utility.dirty_completeness as dc
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_context('paper', font_scale=1.4)
sns.set_style('darkgrid')
%matplotlib inline
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer

df_adult = pd.read_csv('../datasets/adult.csv')
df_list_adult = dc.injection(df_adult, 1, 'adult', 'income')

saved adult-completeness50%
saved adult-completeness60%
saved adult-completeness70%
saved adult-completeness80%
saved adult-completeness90%

In [11]:
working_df = df_list_adult[1]
categorical = ['workclass', 'education', 'maritial-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
numerical = ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']
columns = categorical + numerical

In [22]:
!python utility/tane.py ../../datasets/adult.csv

Traceback (most recent call last):
  File "c:\stefano\VSCodeProjects\DIQ-assignment\code\utility\tane.py", line 186, in <module>
    data2D = read_csv(infile)
  File "c:\Users\PC\anaconda3\envs\dq\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\PC\anaconda3\envs\dq\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\PC\anaconda3\envs\dq\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "c:\Users\PC\anaconda3\envs\dq\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "c:\Users\PC\anaconda3\envs\dq\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "c:\Users\PC\anaconda3\envs\dq\lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "c:\Users\PC\anaconda3\envs\dq\lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../../datasets/adult.csv'

In [ ]:
from utility.utility import iterative_imputation_KNN

imputed_df = iterative_imputation_KNN(working_df, 'income', numerical)

In [13]:
imputed_df.head(20)

,age,workclass,fnlwgt,education,education-num,maritial-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,42.0,Self-emp-not-inc,99185.0,HS-grad,10.086528,Married-civ-spouse,Farming-fishing,Husband,White,Male,2018.469181,0.0,41.713878,United-States,>50K
1,55.0,Private,188300.196587,Masters,14.0,Married-civ-spouse,Prof-specialty,Husband,White,Male,0.0,78.57239,40.0,United-States,>50K
2,40.410927,Private,186975.898753,Masters,10.086528,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,41.713878,United-States,>50K
3,40.410927,Private,208881.0,Some-college,10.0,Married-civ-spouse,Craft-repair,Husband,White,Male,1197.077041,96.948584,41.713878,United-States,<=50K
4,19.0,Private,195681.338327,Some-college,10.0,Never-married,Other-service,Own-child,White,Female,290.03694,58.345175,25.0,United-States,<=50K
5,40.410927,Private,167005.0,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,Male,0.0,95.311342,48.0,United-States,>50K
6,33.0,Private,36539.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,1854.150073,0.0,40.0,United-States,>50K
7,48.0,Private,194088.549037,HS-grad,10.086528,Divorced,Transport-moving,Not-in-family,White,Male,0.0,86.499758,65.0,United-States,<=50K
8,38.429498,Private,196541.298902,Some-college,10.0,Separated,Sales,Not-in-family,White,Female,0.0,0.0,39.611862,United-States,<=50K
9,40.410927,Private,173968.0,HS-grad,10.086528,Married-civ-spouse,Exec-managerial,Husband,White,Male,1591.294372,87.953753,45.0,United-States,<=50K
10,53.0,Private,49715.0,HS-grad,10.086528,Divorced,Transport-moving,Husband,White,Male,0.0,0.0,41.134952,United-States,<=50K
11,51.0,Self-emp-not-inc,180978.301785,Bachelors,10.086528,Married-civ-spouse,Exec-managerial,Husband,White,Male,2491.474859,0.0,41.713878,United-States,>50K
12,34.521187,Private,189815.523454,HS-grad,10.086528,Never-married,Adm-clerical,Own-child,White,Female,0.0,0.0,45.0,United-States,<=50K
13,37.077121,Private,199461.990473,11th,10.0,Divorced,Craft-repair,Own-child,White,Male,0.0,1741.0,40.271101,United-States,<=50K
14,35.873564,Private,201699.224555,HS-grad,11.0,Never-married,Sales,Unmarried,Black,Female,203.697661,61.478655,39.316373,United-States,<=50K
15,40.410927,Private,184653.293798,HS-grad,9.0,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,80.76525,30.0,United-States,<=50K
16,42.0,Private,328239.0,11th,10.086528,Never-married,Other-service,Own-child,White,Male,0.0,71.834504,39.859793,United-States,<=50K
17,39.868179,Local-gov,48055.0,Masters,10.086528,Widowed,Prof-specialty,Husband,White,Male,2312.114957,78.87693,41.134952,United-States,<=50K
18,57.0,Private,169071.0,HS-grad,9.0,Married-civ-spouse,Sales,Husband,White,Male,0.0,0.0,41.713878,United-States,<=50K
19,26.0,Private,222637.0,Some-college,6.0,Never-married,Craft-repair,Not-in-family,White,Male,0.0,88.813134,40.186144,Puerto-Rico,<=50K

In [15]:
from utility.utility import accuracy_assesment

accuracy_assesment([imputed_df], df_adult, columns = columns, numeric_columns=numerical)

[0.9060096246662365]